name: los_registry_service

services:
  eureka-server:
    build: .
    container_name: registry-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - loan-network

networks:
  loan-network:
    name: los-network
    external: true